### ISSUE TITLE
Runs infinite loop

### ISSUE THREAD

**Issue by Shashidhar123** [dmcgarry/kaggle_cooking#1]
1. installed all python packages
2. Downloaded train.json,test.json, train.py and helper.py in same folder. Change the directory and train and test.json dir from ../data/x.json to ./test.json ditto for train.json
3. On command line executed  python train.py
4. Outputs Ingredient Model on the console and runs forever

**Comment by dmcgarry** [comment]
I think you just aren't waiting long enough, using 20 cores this takes about 12 hours to run on a machine with sufficient memory. You could remove the ingredientmodel portion and limit the number of estimators use in each grid to get most of score in a fraction of the time. You can also trim down the number of CV folds.

**Comment by Shashidhar123** [comment]
Thanks dmcgarry, yes it's true I might have waited only about 2 hours. Anyway thanks for sharing the code. It helped me a lot.
